# Generated by Django 5.2.6 on 2025-10-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_author_bookinstance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(
                help_text="Выберите жанр книги", to="catalog.genre"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=13, verbose_name="ISBN"),
        ),
        migrations.AlterField(
            model_name="book",
            name="summary",
            field=models.TextField(help_text="Введите краткое описание книги"),
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "Maintenance"),
                    ("o", "On loan"),
                    ("a", "Available"),
                    ("r", "Reserved"),
                ],
                default="m",
                help_text="Доступность книги",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                help_text="Введите жанр книги (например, Научная фантастика)",
                max_length=200,
            ),
        ),
    ]
