# Generated by Django 5.2.6 on 2025-10-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0003_alter_book_genre_alter_book_isbn_alter_book_summary_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="summary",
            field=models.TextField(
                default="Описание отсутствует",
                help_text="Введите краткое описание книги",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(help_text="Введите жанр книги", max_length=200),
        ),
    ]
